// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApplication.Data;

namespace TestApplication.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppEui");

                    b.Property<string>("AppKey");

                    b.Property<string>("AppSKey");

                    b.Property<string>("DevAdd");

                    b.Property<string>("DevEui");

                    b.Property<string>("DevName");

                    b.Property<string>("FactoryNumber");

                    b.Property<int>("Index");

                    b.Property<string>("NwkSKey");

                    b.Property<int>("ProtocolId");

                    b.Property<string>("Snr");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Models.Protocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<bool>("IsClosed");

                    b.Property<string>("Tester");

                    b.HasKey("Id");

                    b.ToTable("Protocols");
                });

            modelBuilder.Entity("Models.Device", b =>
                {
                    b.HasOne("Models.Protocol", "Protocol")
                        .WithMany("Devices")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
